spring:
  application:
    name: customer-client
  cloud:
    loadbalancer:
      retry:
        max-retries-on-same-service-instance: 0
        max-retries-on-next-service-instance: 3
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8183

logging:
  level:
    root: INFO
    org.springframework: TRACE



feign:
  client:
    config:
      default:
        loggerLevel: FULL
  max-connections: 200


